import QSpecBench.CNOT
import QSpecBench.Pauli
import QSpecBench.Matrix
import QSpecBench.QFT2
import QSpecBench.Stabilizer
import QSpecBench.Quantum.OpenQASM3
import QSpecBench.Teleportation
import QSpecBench.NoCloning
import QSpecBench.Hamiltonian
import QSpecBench.QECDistant
